### ISSUE TITLE
ASCII art docs formatting broken on docs.rs

### ISSUE THREAD

**Issue by repi** [zakarumych/rapid-qoi#2]
Example: https://docs.rs/rapid-qoi/0.4.1/rapid_qoi/index.html

Think one have to put the ASCII art within pre-formatted markdown section (like code) for it to show up well on docs.rs

**Comment by zakarumych** [comment]
Hi. And thanks for noticing!

I will check all documentation to see it is in good shape.

**Comment by zakarumych** [comment]
5087804160e0a0f5d2961b0e4d9f8d52a41f4dcc should fix this.
See on https://docs.rs/rapid-qoi/0.4.2/rapid_qoi/

**Comment by repi** [comment]
sweet, looks good, thanks!
